#!/usr/bin/env bash
# Generate deterministic Road-to-1.0 baseline inventories.
#
# The source pin is initialized once from HEAD and then preserved on later runs.
# Use --refresh-pin only when intentionally moving the reviewed baseline.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ORACLEDB_BASELINE_DIR:-$ROOT/docs/baseline}"
CHECK=false
REFRESH_PIN=false

usage() {
  cat <<'USAGE'
Usage: scripts/gen_baseline.sh [--check] [--refresh-pin]

Writes deterministic baseline artifacts under docs/baseline/ by default.

Options:
  --check        fail if a tracked docs/baseline artifact changes after generation
  --refresh-pin  reset docs/baseline/source_commit.txt to the current HEAD
  -h, --help     show this help

Environment:
  ORACLEDB_BASELINE_DIR  alternate output directory for smoke tests or CI probes
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check) CHECK=true ;;
    --refresh-pin) REFRESH_PIN=true ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "gen-baseline: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "gen-baseline: missing required command: $1" >&2
    exit 2
  }
}

relpath() {
  local path="$1"
  case "$path" in
    "$ROOT"/*) printf '%s\n' "${path#"$ROOT"/}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

need awk
need cargo
need git
need jq
need rg
need rustc

mkdir -p "$OUT"

pin_file="$OUT/source_commit.txt"
if [ "$REFRESH_PIN" = true ] || [ ! -s "$pin_file" ]; then
  source_commit="$(git -C "$ROOT" rev-parse HEAD)"
else
  source_commit="$(tr -d '\n' < "$pin_file")"
fi
printf '%s\n' "$source_commit" > "$pin_file"

metadata="$(cargo metadata --format-version 1 --no-deps)"

cat > "$OUT/README.md" <<'EOF'
# Road-to-1.0 Baseline

Generated by `scripts/gen_baseline.sh`.

These files are deterministic inventories for the reviewed source baseline. Do
not hand-edit them; update them by rerunning the generator. The
`source_commit.txt` pin is intentionally stable across normal runs. Use
`scripts/gen_baseline.sh --refresh-pin` only when intentionally moving the
reviewed baseline.
EOF

{
  printf 'key\tvalue\n'
  printf 'source_commit\t%s\n' "$source_commit"
  printf 'workspace_version\t%s\n' "$(jq -r '.packages | map(.version) | unique | join(",")' <<<"$metadata")"
  printf 'cargo\t%s\n' "$(cargo -V)"
  printf 'rustc\t%s\n' "$(rustc -V)"
  printf 'rustc_host\t%s\n' "$(rustc -vV | awk -F ': ' '$1 == "host" {print $2}')"
  if [ -f "$ROOT/rust-toolchain.toml" ]; then
    printf 'rust_toolchain_file\t%s\n' "$(tr '\n' ' ' < "$ROOT/rust-toolchain.toml" | awk '{$1=$1; print}')"
  fi
} > "$OUT/version_pins.tsv"

{
  printf 'package\tversion\tpublish\tmanifest_path\n'
  jq -r --arg root "$ROOT/" '
    .packages
    | sort_by(.name)[]
    | [
        .name,
        .version,
        (.publish // [] | if type == "array" then join(",") else tostring end),
        (.manifest_path | sub($root; ""))
      ]
    | @tsv
  ' <<<"$metadata"
} > "$OUT/workspace_packages.tsv"

{
  printf 'package\tfeature\tmembers\n'
  jq -r '
    .packages
    | sort_by(.name)[]
    | . as $pkg
    | (.features | to_entries | sort_by(.key)[])
    | [
        $pkg.name,
        .key,
        (.value | sort | join(","))
      ]
    | @tsv
  ' <<<"$metadata"
} > "$OUT/feature_matrix.tsv"

{
  printf 'profile\tcommand\n'
  printf 'minimal\tcargo check -p oracledb --no-default-features\n'
  printf 'default\tcargo check -p oracledb\n'
  printf 'all-features\tcargo check --workspace --all-features\n'
  printf 'protocol-stable\tcargo +stable test -p oracledb-protocol\n'
  printf 'fuzz-build\tcargo fuzz build --target x86_64-unknown-linux-gnu (cwd crates/oracledb-protocol)\n'
} > "$OUT/supported_profiles.tsv"

{
  printf 'target\tpath\n'
  if [ -f "$ROOT/crates/oracledb-protocol/fuzz/Cargo.toml" ]; then
    cargo metadata \
      --manifest-path "$ROOT/crates/oracledb-protocol/fuzz/Cargo.toml" \
      --format-version 1 \
      --no-deps |
      jq -r --arg root "$ROOT/" '
        .packages[0].targets
        | sort_by(.name)[]
        | select(.kind | index("bin"))
        | [.name, (.src_path | sub($root; ""))]
        | @tsv
      '
  fi
} > "$OUT/fuzz_targets.tsv"

{
  printf 'path\ttest_markers\n'
  rg --files "$ROOT/crates" |
    sort |
    while IFS= read -r path; do
      case "$path" in
        *.rs)
          markers="$(
            (rg -n '^[[:space:]]*#\[(tokio::)?test\]' "$path" 2>/dev/null || true) |
              wc -l |
              awk '{print $1}'
          )"
          case "$path" in
            */tests/*|*_tests.rs|*test*.rs)
              printf '%s\t%s\n' "$(relpath "$path")" "$markers"
              ;;
            *)
              if [ "$markers" != "0" ]; then
                printf '%s\t%s\n' "$(relpath "$path")" "$markers"
              fi
              ;;
          esac
          ;;
      esac
    done
} > "$OUT/test_inventory.tsv"

{
  printf 'crate\tpath\tline\titem\n'
  for crate_dir in \
    "$ROOT/crates/oracledb/src" \
    "$ROOT/crates/oracledb-protocol/src" \
    "$ROOT/crates/oracledb-derive/src"
  do
    crate="$(basename "$(dirname "$crate_dir")")"
    rg -n \
      --glob '*.rs' \
      --glob '!**/tests/**' \
      --glob '!**/fuzz/**' \
      '^[[:space:]]*pub(\([^)]*\))?[[:space:]]+(use|mod|struct|enum|trait|type|const|static|async[[:space:]]+fn|fn)[[:space:]]+' \
      "$crate_dir" 2>/dev/null |
      sort |
      while IFS=: read -r path line item; do
        printf '%s\t%s\t%s\t%s\n' "$crate" "$(relpath "$path")" "$line" "$(awk '{$1=$1; print}' <<<"$item")"
      done
  done
} > "$OUT/public_source_items.tsv"

{
  printf 'crate\titems\n'
  awk -F '\t' 'NR > 1 { counts[$1]++ } END { for (crate in counts) print crate "\t" counts[crate] }' \
    "$OUT/public_source_items.tsv" |
    sort
} > "$OUT/public_source_counts.tsv"

if [ "$CHECK" = true ]; then
  case "$OUT" in
    "$ROOT"/*)
      if ! git -C "$ROOT" diff --exit-code -- "$(relpath "$OUT")" >/dev/null; then
        echo "gen-baseline: docs/baseline is out of date; rerun scripts/gen_baseline.sh and commit the result" >&2
        git -C "$ROOT" diff --stat -- "$(relpath "$OUT")" >&2
        exit 1
      fi
      ;;
    *)
      echo "gen-baseline: --check skipped git diff because ORACLEDB_BASELINE_DIR is outside the repo" >&2
      ;;
  esac
fi

echo "gen-baseline: wrote $(relpath "$OUT") for source $source_commit"
