#!/usr/bin/env python3
"""Per-thread decode-throughput comparison for python-oracledb thin mode.

This is the python-oracledb half of the per-thread decode benchmark whose Rust
half is ``crates/oracledb/benches/decode_throughput.rs``. It isolates the raw,
single-threaded *language* win — compiled, no-per-cell-object decode versus an
interpreted decoder that materializes a Python object per cell — with no
concurrency and no GIL hand-off involved on either side. The companion
``compare_concurrent_python.py`` measures the orthogonal *no-GIL concurrency*
axis; this one measures how fast a single connection turns wire bytes into typed
values, which shows up even at one worker.

Both drivers issue the byte-identical SQL to the same container over the same
loopback socket and page the same way (``arraysize`` = ``FETCH_ARRAYSIZE``), so
the only variable is the codec. The workload is a large paged fetch of a mixed
``NUMBER`` + ``VARCHAR2`` + ``DATE`` projection generated by a ``connect by
level`` row source:

  * the row is narrow (5 columns) and paged at a modest arraysize, so no single
    batch is wide enough to matter — the decode volume is large because there are
    many rows (``FETCH_ROWS``), not because any one batch is wide;
  * every cell is touched after ``fetchall`` so the per-cell Python object
    (``int``/``Decimal``, ``str``, ``datetime.datetime``) is forced to exist,
    mirroring the Rust bench's ``touch_all_cells``.

Throughput is ``FETCH_ROWS / wall-clock`` (rows decoded per second on the
client), reported as the median over several passes.

Usage:

    eval "$(ORACLEDB_CONTAINER_NAME=rust-oracledb-lane-1525 \\
            ORACLEDB_HOST_PORT=1525 scripts/container.sh env)"
    .venv-py313/bin/python benches/compare_decode_python.py

Environment (set by ``scripts/container.sh env``):
    PYO_TEST_CONNECT_STRING   host:port/service
    PYO_TEST_MAIN_USER        schema user
    PYO_TEST_MAIN_PASSWORD    schema password

Optional:
    DECODE_ROWS       total rows to fetch per pass (default 300000)
    DECODE_ARRAYSIZE  page size (default 1000)
    DECODE_PASSES     measured passes (default 5)
    DECODE_JSON       if set, write the results as JSON to this path
"""

from __future__ import annotations

import json
import os
import sys
import time
from statistics import median

try:
    import oracledb
except ImportError:  # pragma: no cover - environment guard
    sys.stderr.write(
        "python-oracledb is not installed in this interpreter; "
        "run with the project venv (.venv-py313).\n"
    )
    sys.exit(2)

# Workload shape — kept in lockstep with decode_throughput.rs.
FETCH_ROWS = int(os.environ.get("DECODE_ROWS", "300000"))
FETCH_ARRAYSIZE = int(os.environ.get("DECODE_ARRAYSIZE", "1000"))
PASSES = int(os.environ.get("DECODE_PASSES", "5"))
WARMUP_PASSES = 1


def env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        sys.stderr.write(
            f"skipped: {name} not set (source scripts/container.sh env first)\n"
        )
        sys.exit(0)
    return value


def connect_params() -> dict:
    return {
        "user": env("PYO_TEST_MAIN_USER"),
        "password": env("PYO_TEST_MAIN_PASSWORD"),
        "dsn": env("PYO_TEST_CONNECT_STRING"),
    }


def decode_sql() -> str:
    """Byte-identical to ``decode_throughput.rs``'s ``decode_sql``: a mixed
    NUMBER + VARCHAR2 + DATE projection over a ``connect by level`` generator."""
    return (
        "select "
        "level * 1000003 + 7                          as n0, "
        "level * 31 + 100000                           as n1, "
        "rpad('row' || to_char(level) || '-a', 32, 'x') as v0, "
        "rpad('row' || to_char(level) || '-b', 32, 'y') as v1, "
        "date '2000-01-01' + numtodsinterval(mod(level, 9000), 'day') as d0 "
        f"from dual connect by level <= {FETCH_ROWS}"
    )


def touch_rows(rows) -> int:
    """Consume every cell so the per-cell Python object is forced to exist,
    mirroring the Rust bench's ``touch_all_cells``. python-oracledb has already
    materialized each cell into a Python object by the time ``fetchall`` returns,
    so folding over them forces those objects to be real work. Returns the row
    count."""
    sink = 0
    for row in rows:
        for cell in row:
            if isinstance(cell, str):
                sink += len(cell)
            elif cell is not None:
                # int / Decimal / datetime all support a cheap fold; the point is
                # that python-oracledb already built the object.
                sink += 1
    if sink < 0:  # never true; keeps a clever optimizer from proving sink unused
        raise AssertionError
    return len(rows)


def decode_once(conn, sql: str) -> int:
    cur = conn.cursor()
    cur.arraysize = FETCH_ARRAYSIZE
    cur.prefetchrows = FETCH_ARRAYSIZE
    cur.execute(sql)
    total = touch_rows(cur.fetchall())
    cur.close()
    return total


def main() -> int:
    params = connect_params()
    print(f"python-oracledb {oracledb.__version__} (thin mode) — per-thread decode throughput")
    print(f"dsn={params['dsn']} user={params['user']}")
    print(
        f"workload: paged fetch of {FETCH_ROWS} rows x 5 cols "
        f"(2 NUMBER, 2 VARCHAR2, 1 DATE), arraysize {FETCH_ARRAYSIZE}, single connection"
    )
    print(f"passes: {PASSES} measured (after {WARMUP_PASSES} warmup), median reported\n")

    conn = oracledb.connect(**params)
    sql = decode_sql()

    for _ in range(WARMUP_PASSES):
        rows = decode_once(conn, sql)
        assert rows == FETCH_ROWS, f"warmup decoded {rows}, expected {FETCH_ROWS}"

    throughputs = []
    print(f"{'pass':>5}  {'rows/sec':>16}  {'wall (ms)':>14}")
    for pass_idx in range(1, PASSES + 1):
        start = time.perf_counter()
        rows = decode_once(conn, sql)
        elapsed = time.perf_counter() - start
        assert rows == FETCH_ROWS, f"decoded {rows}, expected {FETCH_ROWS}"
        throughput = rows / max(elapsed, 1e-12)
        throughputs.append(throughput)
        print(f"{pass_idx:>5}  {throughput:>16.0f}  {elapsed * 1e3:>14.1f}")

    conn.close()

    med = median(throughputs)
    best = max(throughputs)
    print(
        f"\nmedian: {med:.0f} rows/sec decoded (best pass {best:.0f}); "
        "single connection, no GIL involved on either side."
    )

    if os.environ.get("DECODE_JSON"):
        with open(os.environ["DECODE_JSON"], "w") as handle:
            json.dump(
                {
                    "rows": FETCH_ROWS,
                    "arraysize": FETCH_ARRAYSIZE,
                    "passes_rows_per_sec": throughputs,
                    "median_rows_per_sec": med,
                    "best_rows_per_sec": best,
                },
                handle,
                indent=2,
            )
        print(f"\nwrote {os.environ['DECODE_JSON']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
