//! Integration tests for the sans-I/O TLS wallet readers, SNI builder and DN
//! matcher, exercised against REAL fixtures generated with openssl (see
//! `crates/oracledb/tests/fixtures/tls/` and `docs/TLS_SETUP.md`).
//!
//! These prove the actual parsing/crypto paths — not mocks. The `cwallet.sso`
//! test is gated on the `experimental` feature.

use std::path::PathBuf;

use oracledb_protocol::tls::dn::{check_cert_dn, check_server_name, name_matches};
use oracledb_protocol::tls::sni::build_sni;
use oracledb_protocol::tls::wallet::{parse_ewallet_pem, resolve_wallet_dir};

fn fixture_dir() -> PathBuf {
    // crates/oracledb-protocol/tests -> crates/oracledb/tests/fixtures/tls
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates/
    p.push("oracledb");
    p.push("tests");
    p.push("fixtures");
    p.push("tls");
    p
}

fn read_fixture(name: &str) -> Vec<u8> {
    let path = fixture_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()))
}

#[test]
fn ewallet_pem_parses_real_cert_and_key() {
    // ewallet.pem = self-signed server cert + private key (mTLS-capable wallet).
    let pem = read_fixture("ewallet.pem");
    let wallet = parse_ewallet_pem(&pem, None).expect("ewallet.pem should parse");
    assert!(
        !wallet.ca_certificates.is_empty(),
        "wallet must expose at least one CA/trust-anchor cert"
    );
    assert!(
        wallet.has_client_identity(),
        "ewallet.pem with a private key must yield a client identity"
    );
    // The first CA cert DER must be a valid X.509 (parse with x509-cert).
    use x509_cert::der::Decode;
    let cert = x509_cert::Certificate::from_der(&wallet.ca_certificates[0])
        .expect("parsed cert DER must be valid X.509");
    let subject = cert.tbs_certificate.subject.to_string();
    assert!(
        subject.contains("db.example.com"),
        "subject was {subject:?}"
    );
}

#[test]
fn ca_only_wallet_is_verify_only() {
    // ca_wallet.pem holds only the CA cert, no key => verify-only.
    let pem = read_fixture("ca_wallet.pem");
    let wallet = parse_ewallet_pem(&pem, None).expect("ca_wallet.pem should parse");
    assert_eq!(wallet.ca_certificates.len(), 1);
    assert!(
        !wallet.has_client_identity(),
        "a CA-only wallet must NOT present a client identity"
    );
}

#[test]
fn sni_string_matches_reference_format() {
    // python-oracledb _calc_sni_data: S{len}.{service}.V3.{version}
    assert_eq!(build_sni("FREEPDB1", None), "S8.FREEPDB1.V3.319");
    assert_eq!(build_sni("svc", Some("dedicated")), "S3.svc.T1.d.V3.319");
}

#[test]
fn dn_match_accepts_matching_subject_dn() {
    // The real leaf subject is "C=US, O=ExampleDB, CN=db.example.com".
    assert!(check_cert_dn(
        "CN=db.example.com,O=ExampleDB,C=US",
        "C=US, O=ExampleDB, CN=db.example.com"
    )
    .is_ok());
}

#[test]
fn dn_match_rejects_wrong_subject_dn() {
    assert!(check_cert_dn(
        "CN=evil.example.com,O=ExampleDB,C=US",
        "C=US, O=ExampleDB, CN=db.example.com"
    )
    .is_err());
}

#[test]
fn name_match_accepts_san_and_wildcard() {
    assert!(check_server_name("db.example.com", &["db.example.com".into()], &[]).is_ok());
    assert!(name_matches("anything.example.com", "*.example.com"));
    assert!(check_server_name("db.example.com", &["evil.example.com".into()], &[]).is_err());
}

#[test]
fn resolve_wallet_dir_precedence() {
    assert_eq!(
        resolve_wallet_dir(Some("/w"), Some("/t")),
        Some("/w".into())
    );
    assert_eq!(resolve_wallet_dir(Some("SYSTEM"), Some("/t")), None);
    assert_eq!(resolve_wallet_dir(None, Some("/t")), Some("/t".into()));
}

#[cfg(feature = "experimental")]
#[test]
fn cwallet_sso_parses_real_oracle_format_wallet() {
    // A genuine cwallet.sso (Oracle SSO outer container wrapping a real
    // PBES2/PBKDF2/AES-256-CBC PKCS#12), generated by docs/TLS_SETUP.md steps.
    let sso = read_fixture("cwallet.sso");
    let wallet = oracledb_protocol::tls::sso::parse_cwallet_sso(&sso)
        .expect("real cwallet.sso should parse end to end");
    assert!(
        !wallet.ca_certificates.is_empty() || !wallet.client_cert_chain.is_empty(),
        "SSO wallet must yield at least one certificate"
    );
    // Validate the extracted cert DER is real X.509.
    use x509_cert::der::Decode;
    let der = wallet
        .ca_certificates
        .first()
        .or_else(|| wallet.client_cert_chain.first())
        .expect("at least one cert");
    let _cert = x509_cert::Certificate::from_der(der).expect("extracted SSO cert must be X.509");
    // The unencrypted keyBag private key must have been extracted.
    assert!(
        wallet.client_private_key.is_some(),
        "SSO wallet with a keyBag must yield the private key"
    );
}

#[cfg(feature = "experimental")]
#[test]
fn cwallet_sso_parses_shrouded_key_wallet() {
    // A cwallet.sso whose inner PKCS#12 stores the private key in a PBES2/AES
    // *shrouded* key bag (the orapki / openssl default), proving the
    // shrouded-key decryption path.
    let sso = read_fixture("cwallet_shrouded.sso");
    let wallet = oracledb_protocol::tls::sso::parse_cwallet_sso(&sso)
        .expect("shrouded-key cwallet.sso should parse");
    assert!(
        wallet.client_private_key.is_some(),
        "shrouded key bag must be decrypted and extracted"
    );
    assert!(
        !wallet.ca_certificates.is_empty(),
        "shrouded-key SSO wallet must still yield certs"
    );
    // The decrypted key must be a valid PKCS#8 PrivateKeyInfo.
    use x509_cert::der::Decode;
    let key_der = wallet
        .client_private_key
        .as_ref()
        .expect("client private key present");
    pkcs8::PrivateKeyInfo::from_der(key_der).expect("decrypted key must be valid PKCS#8");
}
